import process from 'node:process';
import path from 'node:path';
import { execaSync } from 'execa';
import isAbsolute from 'is-absolute';
import minimist from 'minimist';

const argv = minimist(process.argv);
const latexFileFullPath = argv._.at(-1);
const outputDirectoryName = argv['output-directory'] as string | undefined;

if (outputDirectoryName === undefined) {
	throw new Error('Output directory must be specified.');
}

if (latexFileFullPath === undefined || !isAbsolute(latexFileFullPath)) {
	throw new Error('The full path to the LaTeX file must be specified.');
}

execaSync('lualatex', [
	'--shell-escape',
	'--enable-write18',
	'-synctex=1',
	'-interaction=nonstopmode',
	'-file-line-error',
	'-output-directory=out',
	latexFileFullPath,
]);

const workingDir = path.dirname(latexFileFullPath);
const outDir = path.resolve(workingDir, outputDirectoryName);
const filename = path.basename(latexFileFullPath, '.tex');

// Cleans the old artifacts generated by pythontex
execaSync('rm', [
	'-rf',
	`${outDir}/pythontex-files-${filename}`,
	`${outDir}/${filename}.pytxcode`,
]);

execaSync('pythontex', [`${outDir}/${filename}.tex`]);

execaSync('cp', [`${filename}.tex`, `${outDir}/${filename}.tex`]);

execaSync('lualatex', [
	'--shell-escape',
	'--enable-write18',
	'-synctex=1',
	'-interaction=nonstopmode',
	'-file-line-error',
	'-output-directory=out',
	`${outDir}/${filename}.tex`,
]);
